import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    appName: 'Shared Resource Scheduling System',
    appSubtitle: 'Wollo University Resource Booking & Management System',
    loginTitle: 'Sign In to Resource Scheduling System',
    loginSubtitle: 'Enter your credentials to access your account',
    selectRole: 'Select Role',
    username: 'Username:',
    email: 'Email Address:',
    password: 'Password:',
    showPassword: 'Show Password',
    loginAs: 'Login as:',
    loginBtn: 'Login',
    registerBtn: 'Register Here',
    registerTitle: 'Register New User',
    fullName: 'Full Name:',
    department: 'Department:',
    createAccount: 'Create Account',
    signIn: 'Sign In to Platform',
    authenticating: 'Authenticating...',
    quickDemoLogin: 'Quick Login by Role (5 RBAC Roles)',
    switchLanguage: 'ቋንቋ ቀይር (Amharic)',
    currentLanguageLabel: 'English',
    cancel: 'Cancel',
    registering: 'Registering...',
    themeLight: 'Light',
    themeGrey: 'Grey',
    themeDark: 'Dark',
    themeTitle: 'Theme Mode',
    
    // Roles without personal names
    super_admin: 'Super Admin',
    resource_manager: 'Resource Manager',
    department_head: 'Department Head',
    staff: 'Staff Member',
    auditor: 'System Auditor',

    // User Registration & Accounts
    userManagement: 'User Registration & Accounts',
    resourceManagementTab: 'Resource Management & Maintenance',
    registerNewUserBtn: 'Register New User',
    registeredUsersList: 'Registered System Users',
    userRegisteredSuccess: 'New user created successfully!',

    // Role Descriptions for Login
    desc_super_admin: 'Full System Control & User Registration',
    desc_resource_manager: 'Manage Resources, Maintenance & Overrides',
    desc_department_head: 'Approve Department Resource Requests',
    desc_staff: 'Book Equipment, Vehicles & Rooms',
    desc_auditor: 'Read-Only Audit & Compliance Analytics',

    // Navigation
    nav_dashboard: 'Dashboard',
    nav_discovery: 'Book Resource',
    nav_calendar: 'Calendar View',
    nav_my_bookings: 'My Bookings',
    nav_approvals: 'Pending Approvals',
    nav_admin: 'Resource Admin',
    nav_reports: 'Reports & Audits',

    // Header & System
    dbInfo: '',
    notifications: 'Live Notifications',
    noNotifications: 'No new notifications',
    signOut: 'Sign Out',
    activeUser: 'Logged in as',
    invalidCredentials: 'Invalid credentials or login failed',
    emailSettings: 'Email Notification Settings',
    emailModalDesc: 'Set your real email address to receive instant HTML notifications for booking confirmations, approval statuses, cancellations, and waitlist alerts.',
    realEmailLabel: 'Real Notification Email Address:',
    sendTestEmail: 'Send Test Email',
    saveEmail: 'Save Email',
    savingEmail: 'Saving...',
    emailSuccess: 'Email updated successfully!',
    emailError: 'Failed to update email',
    etherealPreview: '🔗 Click here to preview sent email on Ethereal',

    // Dashboard Overview
    welcomeBack: 'Welcome back',
    roleLabel: 'Role',
    deptLabel: 'Department',
    bookResourceBtn: 'Book a Resource',
    activeResources: 'Active Resources',
    bookingsToday: 'Bookings Today',
    capacityUtilization: 'Capacity Utilization',
    noShowRate: 'No-Show Penalty Rate',
    pendingApprovals: 'Pending Approvals',
    activeUpcomingReservations: 'Active & Upcoming Reservations',
    viewCalendar: 'View Calendar',
    noUpcomingBookings: 'No upcoming bookings found for today.',
    bookingRef: 'Booking Ref',
    resourceName: 'Resource Name',
    category: 'Category',
    bookedBy: 'Booked By',
    timeWindow: 'Time Window',
    status: 'Status',

    // Resource Catalog
    resourceCatalogTitle: 'Resource Discovery Catalog',
    resourceCatalogDesc: 'Browse available rooms, fleet vehicles, labs, and equipment.',
    searchPlaceholder: 'Search by resource name, ID, or location...',
    minCapacity: 'Min Capacity:',
    allResources: 'All Resources',
    meetingRooms: 'Meeting Room',
    conferenceHalls: 'Conference Hall',
    trainingLabs: 'Training Lab',
    fleetVehicles: 'Vehicle',
    equipment: 'Equipment',
    capacity: 'Capacity',
    hours: 'Hours',
    approvalRequired: 'Approval Required',
    readOnlyAuditor: 'Read-Only Mode (Auditor)',
    reserveResource: 'Reserve Resource',
    noResourcesFound: 'No resources found matching the specified filters.',
    statusAvailable: 'Available',
    statusPending: 'Pending Approval',
    statusInUse: 'In Use',
    availableNow: 'Available Now',
    availableAfterPrefix: 'Available after',
    availableUntilPrefix: 'Available until',
    filterAllStatuses: 'All Statuses',
    filterAvailableOnly: '🟢 Available',
    filterPendingOnly: '🟡 Pending Approval',
    filterInUseOnly: '🔴 In Use',
    currentOccupant: 'Currently occupied by',
    pendingRequester: 'Requested by (Pending)',
    readyToBook: 'Free and ready to reserve',
    reserveSlot: 'Reserve Slot',
    joinWaitlistBtn: 'Join Waitlist',

    // Calendar View
    today: 'Today',
    daily: 'Daily',
    weekly: 'Weekly',
    legendAvailable: 'Available',
    legendBooked: 'Booked',
    legendPending: 'Pending Approval',
    legendMaintenance: 'Maintenance',
    allResourcesFilter: 'All Resources',
    available: 'Available',
    bookedByTitle: 'Booked by',

    // My Bookings View
    myBookingsTitle: 'My Reservations & Bookings',
    myBookingsDesc: 'Manage your active bookings, check-in, and review history.',
    noBookingsFound: 'You have no active or past bookings.',
    titleHeader: 'Title',
    startTimeHeader: 'Start Time',
    endTimeHeader: 'End Time',
    statusHeader: 'Status',
    actionsHeader: 'Actions',
    checkInBtn: 'Check-In',
    checkOutBtn: 'Check-Out',
    cancelBtn: 'Cancel',
    confirmCancel: 'Are you sure you want to cancel this booking?',

    // Approvals Queue
    approvalsTitle: 'Approvals Management Queue',
    approvalsDesc: 'Review and approve/reject resource booking requests requiring authorization.',
    noPendingApprovals: 'No pending approval requests requiring action.',
    requester: 'Requester',
    timeRequested: 'Time Requested',
    approveBtn: 'Approve',
    rejectBtn: 'Reject',
    holdBtn: 'Hold',
    rejectionModalTitle: 'Rejection Reason Required',
    rejectionReasonLabel: 'Mandatory Reason for Rejection (sent to staff member)',
    rejectionPlaceholder: 'e.g. Executive priority conflict or department budget restrictions.',
    confirmRejection: 'Confirm Rejection',

    // Admin Management
    adminTitle: 'Resource Management & Maintenance',
    adminDesc: 'Configure system resources, operating parameters, and maintenance blocks.',
    addNewResource: 'Add New Resource',
    viewDetails: 'View Details',
    resourceDetailsTitle: 'Resource Details & Specifications',
    editResource: 'Edit Resource',
    deleteResource: 'Delete Resource',
    confirmDeleteResource: 'Are you sure you want to delete this resource?',
    idHeader: 'ID',
    typeHeader: 'Type',
    locationHeader: 'Location',
    approvalReqHeader: 'Approval Req.',
    scheduleMaintenanceBlock: 'Schedule Maintenance Block',
    createResourceTitle: 'Create New System Resource',
    resourceType: 'Resource Type',
    categoryName: 'Category Name',
    requiresApprovalCheck: 'Requires Approval Workflow',
    requiresCheckinCheck: 'Requires 15-Min Check-In',
    createResourceBtn: 'Create Resource',
    blockStartLabel: 'Start Date & Time',
    blockEndLabel: 'End Date & Time',
    blockReasonLabel: 'Maintenance Reason',
    scheduleBlockBtn: 'Schedule Block',

    // Reports & Audits
    reportsTitle: 'Reports, Analytics & Audit Logs',
    reportsDesc: 'Resource capacity planning, department usage matrix, and full audit logs.',
    exportCsvBtn: 'Export Bookings CSV',
    exportPdfCsv: 'Export Bookings CSV',
    resourceHoursBooked: 'Resource Hours Booked',
    totalBookings: 'Total Bookings',
    hoursBooked: 'Hours Booked',
    hrsBooked: 'Hours Booked',
    deptCostMatrix: 'Department Cost Allocation Matrix',
    deptUtilizationBreakdown: 'Department Usage Breakdown',
    totalHours: 'Total Hours',
    auditLogsTitle: 'Full Audit Log Trail',
    auditTrail: 'Audit Log Trail',
    userHeader: 'User',
    actionHeader: 'Action',
    detailsHeader: 'Details',
    timestampHeader: 'Timestamp',

    // Booking Modal & Actions
    bookResourceModalTitle: 'Book Resource:',
    locationLabel: 'Location:',
    maxCapLabel: 'Max Cap:',
    bookOnBehalf: 'Book on Behalf of User (Admin Privileges)',
    self: 'Self',
    meetingTitleLabel: 'Meeting Title / Agenda (Mandatory, max 200 chars)',
    meetingTitlePlaceholder: 'e.g. Q3 Strategic Planning & Budget Review',
    startDateLabel: 'Start Date & Time',
    endDateLabel: 'End Date & Time',
    attendeesLabel: 'Number of Attendees',
    recurringLabel: 'Recurring Option',
    oneTimeBooking: 'One-time Booking',
    dailyRecurrence: 'Daily (Max 12 weeks)',
    weeklyRecurrence: 'Weekly (Max 12 weeks)',
    monthlyRecurrence: 'Monthly (Max 12 weeks)',
    specialRequirementsLabel: 'Special Requirements / Equipment Notes (Optional)',
    specialRequirementsPlaceholder: 'e.g. Additional seating needed, video conference link setup...',
    validatingBooking: 'Validating & Booking...',
    submitForApproval: 'Submit for Approval',
    confirmReservation: 'Confirm Reservation',
    rescheduleBtn: 'Reschedule',
    rescheduleTitle: 'Reschedule Booking',
    newStartTime: 'New Start Time',
    newEndTime: 'New End Time',
    confirmReschedule: 'Confirm Reschedule',
    bookingRescheduledSuccess: 'Booking rescheduled successfully!',

    // Check-In & Check-Out Modal
    checkInTitle: 'Check-In to Booking',
    checkOutTitle: 'Check-Out & Resource Feedback',
    gracePeriodActive: 'Grace Period Active (15 Min Window)',
    qrCodeVerified: 'QR CODE VERIFIED',
    scanQrCode: 'Scan QR Code',
    webCheckIn: 'Web Check-In',
    checkInConfirmed: 'Check-in confirmed successfully!',
    checkOutCompleted: 'Check-out & feedback submitted!',
    rateExperience: 'Rate Resource Experience (1 to 5 Stars)',
    commentsFeedbackLabel: 'Comments & Maintenance Feedback (Optional)',
    commentsPlaceholder: 'e.g. Room was clean, projector worked perfectly.',
    submitFeedback: 'Submit Check-Out & Feedback',

    // Conflict Modal & Waitlist
    conflictDetected: 'Conflict Detected!',
    conflictDetectedTitle: 'Conflict Detected!',
    conflictDetectedDesc: 'The resource is unavailable during your requested time window.',
    unavailableNotice: 'is unavailable during your requested time window.',
    calculatingSuggestions: 'Calculating next available times & alternative resources...',
    recommendedSlotLabel: 'RECOMMENDED NEXT AVAILABLE TIME SLOT',
    recommendedNextSlot: 'RECOMMENDED NEXT AVAILABLE TIME SLOT',
    sameResourceLabel: 'Same resource',
    suggestedAdjacentSlots: 'Suggested Adjacent Slots:',
    suggestedAdjacent: 'Suggested Adjacent Slots:',
    alternativeResourcesTitle: 'Alternative Available Resources (Same Category):',
    alternativeResources: 'Alternative Available Resources (Same Category):',
    noAlternativesFound: 'No alternative resources available at this exact time.',
    bookAlternative: 'Book Alternative',
    preferExactTime: 'Prefer this exact time slot & resource?',
    joinWaitlistQuestion: 'Prefer this exact time slot & resource?',
    joinWaitlistDesc: 'Join waitlist. If current booking is cancelled, you will be auto-notified.',
    joinWaitlistBtn: 'Join Waitlist',
    joinWaitlist: 'Join Waitlist',
    waitlistSuccess: 'Successfully added to waitlist! You will be notified if a slot opens.',
    waitlistAdded: 'Successfully added to waitlist! You will be notified if a slot opens.',

    // App Messages
    loadingApp: 'Loading Shared Resource Scheduling Engine...',
    bookingConfirmedRef: 'Booking confirmed! Reference Number:',
    waitlistJoinedSuccess: 'Successfully joined resource waitlist!',

    // Forgot & Reset Password
    forgotPassword: 'Forgot Password?',
    forgotPasswordTitle: 'Reset Your Password',
    forgotPasswordSubtitle: 'Enter your registered email address and we will send you a password reset link.',
    sendResetLink: 'Send Reset Link',
    sendingResetLink: 'Sending Reset Link...',
    backToLogin: 'Back to Sign In',
    resetPasswordTitle: 'Set New Password',
    resetPasswordSubtitle: 'Create a new secure password for your account.',
    newPasswordLabel: 'New Password:',
    confirmPasswordLabel: 'Confirm New Password:',
    setNewPasswordBtn: 'Update Password',
    updatingPassword: 'Updating Password...',
    passwordResetSuccess: 'Password updated successfully! Redirecting to login...',
    passwordsDoNotMatch: 'Passwords do not match. Please check and try again.',
    passwordLengthError: 'Password must be at least 8 characters long and contain letters, numbers, and symbols (@, #, $, etc.).',
    passwordRequirements: 'Password Requirements:',
    reqMin8: 'At least 8 characters',
    reqLetter: 'Contains letters (a-z, A-Z)',
    reqNumber: 'Contains numbers (0-9)',
    reqSymbol: 'Contains special symbol (!@#$%^&*)',
    invalidResetLink: 'This password reset link is invalid or has expired.',
    resetLinkSentSuccess: 'A password reset link has been sent to your email. Please check your inbox (or spam) and click the link to reset your password.'
  },
  am: {
    appName: 'የጋራ ሀብት ማኔጅመንት ሲስተም',
    appSubtitle: 'የወሎ ዩኒቨርሲቲ የጋራ ሀብቶች ማዕከላዊ ቦታ ማስያዣ ሲስተም',
    loginTitle: 'ወደ ሲስተሙ ይግቡ',
    loginSubtitle: 'ሲስተሙን ለመጠቀም የይለፍ ቃልዎን እና ኢሜይልዎን ያስገቡ',
    selectRole: 'የመግቢያ ሚና ይምረጡ',
    username: 'የተጠቃሚ ስም:',
    email: 'ኢሜይል አድራሻ:',
    password: 'የይለፍ ቃል:',
    showPassword: 'የይለፍ ቃል አሳይ',
    loginAs: 'መግቢያ እንደ:',
    loginBtn: 'ይግቡ',
    registerBtn: 'እዚህ ይመዝገቡ (Register Here)',
    registerTitle: 'አዲስ ተጠቃሚ መመዝገቢያ',
    fullName: 'ሙሉ ስም:',
    department: 'ክፍል / ዲፓርትመንት:',
    createAccount: 'አካውንት ፍጠር',
    signIn: 'ወደ ሲስተሙ ግባ',
    authenticating: 'በማረጋገጥ ላይ...',
    quickDemoLogin: 'በሚናዎች ፈጣን መግቢያ (5 RBAC ሚናዎች)',
    switchLanguage: 'Switch to English',
    currentLanguageLabel: 'አማርኛ',
    cancel: 'ሰርዝ',
    registering: 'በመመዝገብ ላይ...',
    themeLight: 'ብርሃን (Light)',
    themeGrey: 'ግሬይ (Grey)',
    themeDark: 'ጨለማ (Dark)',
    themeTitle: 'የቅርጽ ሁኔታ (Theme)',

    // Roles
    super_admin: 'ዋና አስተዳዳሪ (Super Admin)',
    resource_manager: 'የሀብት አስተዳዳሪ (Resource Manager)',
    department_head: 'የክፍል ኃላፊ (Dept Head)',
    staff: 'ሰራተኛ (Staff Member)',
    auditor: 'ኦዲተር (System Auditor)',

    // User Registration & Accounts
    userManagement: 'የተጠቃሚዎች ምዝገባ እና አካውንቶች',
    resourceManagementTab: 'የሀብቶች አስተዳደር እና ጥገና',
    registerNewUserBtn: 'አዲስ ተጠቃሚ መመዝገብ',
    registeredUsersList: 'በሲስተሙ የተመዘገቡ ተጠቃሚዎች',
    userRegisteredSuccess: 'አዲስ ተጠቃሚ አካውንት በተሳካ ሁኔታ ተፈጥሯል!',

    // Role Descriptions for Login
    desc_super_admin: 'ሙሉ የሲስተም ቁጥጥር እና ተጠቃሚዎችን መመዝገቢያ',
    desc_resource_manager: 'ሀብቶችን ማስተዳደር እና ጥገና መቆጣጠር',
    desc_department_head: 'የክፍሉን ቦታ ማስያዝ ጥያቄዎች ማጽደቅ',
    desc_staff: 'መኪናዎችን፣ አዳራሾችን እና እቃዎችን ማስያዝ',
    desc_auditor: 'የኦዲት እና ትንታኔ ሪፖርቶችን መመልከት ብቻ',

    // Navigation
    nav_dashboard: 'ዳሽቦርድ',
    nav_discovery: 'ሀብት ያዙ',
    nav_calendar: 'የካላንደር እይታ',
    nav_my_bookings: 'የእኔ ቦታ ማስያዞች',
    nav_approvals: 'ማጽደቂያዎች',
    nav_admin: 'የሀብት መቆጣጠሪያ',
    nav_reports: 'ሪፖርቶች እና ኦዲት',

    // Header & System
    dbInfo: '',
    notifications: 'ቀጥታ ማሳወቂያዎች',
    noNotifications: 'አዲስ ማሳወቂያ የለም',
    signOut: 'ውጣ',
    activeUser: 'የገቡት እንደ',
    invalidCredentials: 'የተሳሳተ ኢሜይል ወይም የይለፍ ቃል',
    emailSettings: 'የኢሜይል ማሳወቂያ ቅንብሮች',
    emailModalDesc: 'የቦታ ማስያዝ ማረጋገጫዎች፣ የማጽደቅ ሁኔታዎች እና ማሳወቂያዎችን ለማግኘት እውነተኛ ኢሜይልዎን ያስገቡ።',
    realEmailLabel: 'እውነተኛ የማሳወቂያ ኢሜይል አድራሻ:',
    sendTestEmail: 'ሙከራ ኢሜይል ላክ',
    saveEmail: 'ኢሜይል አስቀምጥ',
    savingEmail: 'በማስቀመጥ ላይ...',
    emailSuccess: 'ኢሜይል በተሳካ ሁኔታ ተዘምኗል!',
    emailError: 'ኢሜይል ማዘመን አልተቻለም',
    etherealPreview: '🔗 የተላከውን ኢሜይል በEthereal ቅድመ-ዕይታ ይመልከቱ',

    // Dashboard Overview
    welcomeBack: 'እንኳን ደህና መጡ',
    roleLabel: 'ሚና',
    deptLabel: 'ክፍል',
    bookResourceBtn: 'ሀብት ያዙ',
    activeResources: 'ንቁ ሀብቶች',
    bookingsToday: 'የዛሬ ቦታ ማስያዞች',
    capacityUtilization: 'የአጠቃቀም መጠን',
    noShowRate: 'ያልተገኙበት ቅጣት መጠን',
    pendingApprovals: 'የሚጠበቁ ማጽደቂያዎች',
    activeUpcomingReservations: 'ንቁ እና የሚመጡ ቦታ ማስያዞች',
    viewCalendar: 'ካላንደር ይመልከቱ',
    noUpcomingBookings: 'ለዛሬ ምንም የሚመጣ ቦታ ማስያዝ የለም።',
    bookingRef: 'የማስያዣ መለያ',
    resourceName: 'የሀብቱ ስም',
    category: 'ምድብ',
    bookedBy: 'ያስያዘው ሰው',
    timeWindow: 'የጊዜ ክልል',
    status: 'ሁኔታ',

    // Resource Catalog
    resourceCatalogTitle: 'የሀብቶች ካታሎግ',
    resourceCatalogDesc: 'የሚገኙ አዳራሾችን፣ መኪናዎችን፣ ላቦራቶሪዎችን እና እቃዎችን ይፈልጉ።',
    searchPlaceholder: 'በሀብት ስም፣ መለያ ወይም ቦታ ይፈልጉ...',
    minCapacity: 'አነስተኛ የመያዝ አቅም:',
    allResources: 'ሁሉም ሀብቶች',
    meetingRooms: 'የስብሰባ ክፍል',
    conferenceHalls: 'የኮንፈረንስ አዳራሽ',
    trainingLabs: 'የስልጠና ላቦራቶሪ',
    fleetVehicles: 'ተሽከርካሪ',
    equipment: 'መሣሪያ / እቃ',
    capacity: 'አቅም',
    hours: 'ሰዓታት',
    approvalRequired: 'ማጽደቅ ያስፈልገዋል',
    readOnlyAuditor: 'የመመልከት ብቻ (ኦዲተር)',
    reserveResource: 'ሀብቱን ያዙ',
    noResourcesFound: 'ከተመረጡት ማጣሪያዎች ጋር የሚጣጣም ሀብት አልተገኘም።',
    statusAvailable: 'ክፍት',
    statusPending: 'ማጽደቅ የሚጠብቅ',
    statusInUse: 'ተይዟል / በስራ ላይ',
    availableNow: 'አሁን ክፍት ነው',
    availableAfterPrefix: 'ከ',
    availableUntilPrefix: 'እስከ',
    filterAllStatuses: 'ሁሉም ሁኔታዎች',
    filterAvailableOnly: '🟢 ክፍት ብቻ',
    filterPendingOnly: '🟡 ማጽደቅ የሚጠብቁ',
    filterInUseOnly: '🔴 ተይዟል / በስራ ላይ',
    currentOccupant: 'በአሁኑ ሰዓት እየተጠቀሙበት ያለ',
    pendingRequester: 'ማጽደቅ የሚጠብቅ ጥያቄ ያቀረበው',
    readyToBook: 'ነፃ እና ለማስያዝ ዝግጁ',
    reserveSlot: 'ቦታውን ያዙ',
    joinWaitlistBtn: 'ተጠባባቂ ዝርዝር ውስጥ ይግቡ',

    // Calendar View
    today: 'ዛሬ',
    daily: 'በቀን',
    weekly: 'በሳምንት',
    legendAvailable: 'ክፍት',
    legendBooked: 'ተይዟል',
    legendPending: 'ማጽደቅ የሚጠብቅ',
    legendMaintenance: 'በጥገና ላይ',
    allResourcesFilter: 'ሁሉም ሀብቶች',
    available: 'ክፍት',
    bookedByTitle: 'የያዘው',

    // My Bookings View
    myBookingsTitle: 'የእኔ ቦታ ማስያዞች',
    myBookingsDesc: 'ቦታ ማስያዞችዎን ያስተዳድሩ፣ ቼክ-ኢን ያድርጉ እና ታሪክዎን ይመልከቱ።',
    noBookingsFound: 'ምንም ንቁ ወይም ያለፈ ቦታ ማስያዝ የለዎትም።',
    titleHeader: 'ርዕስ',
    startTimeHeader: 'የመጀመሪያ ሰዓት',
    endTimeHeader: 'የመጨረሻ ሰዓት',
    statusHeader: 'ሁኔታ',
    actionsHeader: 'እርምጃዎች',
    checkInBtn: 'ቼክ-ኢን',
    checkOutBtn: 'ቼክ-አውት',
    cancelBtn: 'ሰርዝ',
    confirmCancel: 'እርግጠኛ ነዎት ይህን ቦታ ማስያዝ መሰረዝ ይፈልጋሉ?',

    // Approvals Queue
    approvalsTitle: 'የማጽደቂያዎች አስተዳደር Queue',
    approvalsDesc: 'ፈቃድ የሚያስፈልጋቸውን የሀብት ጥያቄዎች ይመልከቱ እና ያጽድቁ/ይሰርዙ።',
    noPendingApprovals: 'ምንም የሚጠበቅ የማጽደቅ ጥያቄ የለም።',
    requester: 'ጠያቂ',
    timeRequested: 'የተጠየቀበት ሰዓት',
    approveBtn: 'አጽድቅ',
    rejectBtn: 'ውድቅ አድርግ',
    holdBtn: 'አቆይ',
    rejectionModalTitle: 'የውድቅ ማድረጊያ ምክንያት ያስፈልጋል',
    rejectionReasonLabel: 'ለሰራተኛው የሚላክ ውድቅ የማድረጊያ ምክንያት',
    rejectionPlaceholder: 'ምሳሌ፦ የቅድሚያ ስብሰባ ግጭት ወይም የዲፓርትመንት የበጀት ገደብ።',
    confirmRejection: 'ውድቅ ማድረጉን አረጋግጥ',

    // Admin Management
    adminTitle: 'የሀብት አስተዳደር እና ጥገና',
    adminDesc: 'የሲስተም ሀብቶችን፣ የሥራ መለኪያዎችን እና የጥገና ጊዜያትን ያዋቅሩ።',
    addNewResource: 'አዲስ ሀብት ጨምር',
    viewDetails: 'ዝርዝር ይመልከቱ',
    resourceDetailsTitle: 'የሀብቱ ሙሉ ዝርዝር መረጃ',
    editResource: 'ሀብቱን አስተካክል',
    deleteResource: 'ሀብቱን ሰርዝ',
    confirmDeleteResource: 'እርግጠኛ ነዎት ይህን ሀብት መሰረዝ ይፈልጋሉ?',
    idHeader: 'መለያ ID',
    typeHeader: 'ዓይነት',
    locationHeader: 'ቦታ',
    approvalReqHeader: 'ማጽደቅ ያስፈልጋል',
    scheduleMaintenanceBlock: 'የጥገና ጊዜ መዝግብ',
    createResourceTitle: 'አዲስ የሲስተም ሀብት ፍጠር',
    resourceType: 'የሀብት ዓይነት',
    categoryName: 'የምድብ ስም',
    requiresApprovalCheck: 'የማጽደቅ ሂደት ያስፈልገዋል',
    requiresCheckinCheck: 'የ15 ደቂቃ ቼክ-ኢን ያስፈልገዋል',
    createResourceBtn: 'ሀብት ፍጠር',
    blockStartLabel: 'የመጀመሪያ ቀን እና ሰዓት',
    blockEndLabel: 'የመጨረሻ ቀን እና ሰዓት',
    blockReasonLabel: 'የጥገና ምክንያት',
    scheduleBlockBtn: 'ጥገና መዝግብ',

    // Reports & Audits
    reportsTitle: 'ሪፖርቶች፣ ትንታኔዎች እና የኦዲት መዝገቦች',
    reportsDesc: 'የሀብት አጠቃቀም እቅድ፣ የክፍሎች አጠቃቀም ማትሪክስ እና የኦዲት መዝገቦች።',
    exportCsvBtn: 'ቦታ ማስያዞችን በCSV አውርድ',
    exportPdfCsv: 'ቦታ ማስያዞችን በCSV አውርድ',
    resourceHoursBooked: 'የተያዙ ሰዓታት በሀብት',
    totalBookings: 'ጠቅላላ ቦታ ማስያዞች',
    hoursBooked: 'የተያዙ ሰዓታት',
    hrsBooked: 'የተያዙ ሰዓታት',
    deptCostMatrix: 'የክፍሎች አጠቃቀም ማትሪክስ',
    deptUtilizationBreakdown: 'የክፍሎች አጠቃቀም ዝርዝር',
    totalHours: 'ጠቅላላ ሰዓታት',
    auditLogsTitle: 'ሙሉ የኦዲት መዝገብ',
    auditTrail: 'የኦዲት መዝገብ',
    userHeader: 'ተጠቃሚ',
    actionHeader: 'እርምጃ',
    detailsHeader: 'ዝርዝር',
    timestampHeader: 'ቀንና ሰዓት',

    // Booking Modal & Actions
    bookResourceModalTitle: 'ሀብት ያዙ:',
    locationLabel: 'ቦታ:',
    maxCapLabel: 'ከፍተኛ አቅም:',
    bookOnBehalf: 'በሌላ ተጠቃሚ ስም ያዙ (የአስተዳዳሪ ፈቃድ)',
    self: 'ለራሴ',
    meetingTitleLabel: 'የስብሰባው ርዕስ / አጀንዳ (ግዴታ)',
    meetingTitlePlaceholder: 'ምሳሌ፦ የ3ኛው ሩብ ዓመት ስትራቴጂካዊ እቅድ',
    startDateLabel: 'የመጀመሪያ ቀን እና ሰዓት',
    endDateLabel: 'የመጨረሻ ቀን እና ሰዓት',
    attendeesLabel: 'የተሳታፊዎች ብዛት',
    recurringLabel: 'የመደጋገም አማራጭ',
    oneTimeBooking: 'አንድ ጊዜ ብቻ',
    dailyRecurrence: 'በየቀኑ (ከፍተኛ 12 ሳምንታት)',
    weeklyRecurrence: 'በየሳምንቱ (ከፍተኛ 12 ሳምንታት)',
    monthlyRecurrence: 'በየወሩ (ከፍተኛ 12 ሳምንታት)',
    specialRequirementsLabel: 'ልዩ ፍላጎቶች / የመሣሪያ ማስታወሻዎች (አማራጭ)',
    specialRequirementsPlaceholder: 'ምሳሌ፦ ተጨማሪ ወንበሮች ያስፈልጋሉ፣ የቪዲዮ ኮንፈረንስ ሊንክ...',
    validatingBooking: 'በማረጋገጥ ላይ...',
    submitForApproval: 'ለማጽደቅ ላክ',
    confirmReservation: 'ቦታ ማስያዙን አረጋግጥ',
    rescheduleBtn: 'የጊዜ ማስተካከያ',
    rescheduleTitle: 'የቦታ ማስያዝ ጊዜ ማስተካከያ',
    newStartTime: 'አዲስ የመጀመሪያ ሰዓት',
    newEndTime: 'አዲስ የመጨረሻ ሰዓት',
    confirmReschedule: 'የጊዜ ማስተካከያውን አረጋግጥ',
    bookingRescheduledSuccess: 'የቦታ ማስያዝ ጊዜው በተሳካ ሁኔታ ተቀይሯል!',

    // Check-In & Check-Out Modal
    checkInTitle: 'ወደ ቦታ ማስያዣው ቼክ-ኢን ያድርጉ',
    checkOutTitle: 'ቼክ-አውት እና አስተያየት ይስጡ',
    gracePeriodActive: 'የ15 ደቂቃ የቼክ-ኢን ጊዜ ክፍት ነው',
    qrCodeVerified: 'QR ኮድ ተረጋገጠ',
    scanQrCode: 'QR ኮድ ስካን አድርግ',
    webCheckIn: 'በዌብ ቼክ-ኢን አድርግ',
    checkInConfirmed: 'ቼክ-ኢን በተሳካ ሁኔታ ተጠናቋል!',
    checkOutCompleted: 'ቼክ-አውት እና አስተያየት በተሳካ ሁኔታ ተልኳል!',
    rateExperience: 'የሀብቱን ሁኔታ ይገምግሙ (ከ 1 እስከ 5 ኮከብ)',
    commentsFeedbackLabel: 'አስተያየት እና የጥገና ጥቆማ (አማራጭ)',
    commentsPlaceholder: 'ምሳሌ፦ ክፍሉ ንፁህ ነበር፣ ፕሮጀክተሩ በጥሩ ሁኔታ ሠርቷል።',
    submitFeedback: 'ቼክ-አውት አድርግ እና አስተያየት ላክ',

    // Conflict Modal & Waitlist
    conflictDetected: 'የጊዜ ግጭት ተፈጥሯል!',
    conflictDetectedTitle: 'የጊዜ ግጭት ተፈጥሯል!',
    conflictDetectedDesc: 'በተጠየቀው ሰዓት ላይ ሀብቱ ክፍት አይደለም።',
    unavailableNotice: 'በተጠየቀው ሰዓት ላይ ሀብቱ ክፍት አይደለም።',
    calculatingSuggestions: 'ቀጣይ ክፍት ሰዓቶችን እና አማራጭ ሀብቶችን በመፈለግ ላይ...',
    recommendedSlotLabel: 'የሚመከር ቀጣይ ክፍት ሰዓት',
    recommendedNextSlot: 'የሚመከር ቀጣይ ክፍት ሰዓት',
    sameResourceLabel: 'ተመሳሳይ ሀብት',
    suggestedAdjacentSlots: 'የተጠቆሙ አቅራቢያ ሰዓታት:',
    suggestedAdjacent: 'የተጠቆሙ አቅራቢያ ሰዓታት:',
    alternativeResourcesTitle: 'አማራጭ ክፍት ሀብቶች (ተመሳሳይ ምድብ):',
    alternativeResources: 'አማራጭ ክፍት ሀብቶች (ተመሳሳይ ምድብ):',
    noAlternativesFound: 'በዚህ ሰዓት ምንም አማራጭ ሀብት አልተገኘም።',
    bookAlternative: 'አማራጩን ያዙ',
    preferExactTime: 'በዚህ ሰዓት ተመሳሳይ ሀብት ይፈልጋሉ?',
    joinWaitlistQuestion: 'በዚህ ሰዓት ተመሳሳይ ሀብት ይፈልጋሉ?',
    joinWaitlistDesc: 'የተጠባባቂ ዝርዝር ይግቡ። ቦታው ክፍት ሲሆን ማሳወቂያ ይደርስዎታል።',
    joinWaitlistBtn: 'ተጠባባቂ ዝርዝር ግባ',
    joinWaitlist: 'ተጠባባቂ ዝርዝር ግባ',
    waitlistSuccess: 'በተጠባባቂ ዝርዝር ውስጥ በተሳካ ሁኔታ ተመዝግበዋል!',
    waitlistAdded: 'በተጠባባቂ ዝርዝር ውስጥ በተሳካ ሁኔታ ተመዝግበዋል!',

    // App Messages
    loadingApp: 'የጋራ ሀብት ማኔጅመንት ሲስተም በመጫን ላይ...',
    bookingConfirmedRef: 'ቦታ ማስያዙ ተረጋገጠ! የመለያ ቁጥር:',
    waitlistJoinedSuccess: 'በተጠባባቂ ዝርዝር ውስጥ በተሳካ ሁኔታ ተመዝግበዋል!',

    // Forgot & Reset Password
    forgotPassword: 'የይለፍ ቃል ረሱ? (Forgot Password)',
    forgotPasswordTitle: 'የይለፍ ቃልዎን ይቀይሩ',
    forgotPasswordSubtitle: 'የተመዘገቡበትን ኢሜይል ያስገቡ፤ የይለፍ ቃል መቀየሪያ ሊንክ እንልክልዎታለን።',
    sendResetLink: 'የይለፍ ቃል መቀየሪያ ሊንክ ላክ',
    sendingResetLink: 'ሊንኩን በመላክ ላይ...',
    backToLogin: 'ወደ መግቢያ ተመለስ',
    resetPasswordTitle: 'አዲስ የይለፍ ቃል ያስገቡ',
    resetPasswordSubtitle: 'ለአካውንትዎ አዲስ ጠንካራ የይለፍ ቃል ይፍጠሩ።',
    newPasswordLabel: 'አዲስ የይለፍ ቃል (New Password):',
    confirmPasswordLabel: 'የይለፍ ቃሉን ያረጋግጡ (Confirm Password):',
    setNewPasswordBtn: 'የይለፍ ቃሉን አዘምን',
    updatingPassword: 'የይለፍ ቃሉን በማዘመን ላይ...',
    passwordResetSuccess: 'የይለፍ ቃልዎ በተሳካ ሁኔታ ተቀይሯል! ወደ መግቢያ ገጽ እየተላለፉ ነው...',
    passwordsDoNotMatch: 'ያስገቧቸው የይለፍ ቃሎች አይመሳሰሉም። እባክዎ እንደገና ይሞክሩ።',
    passwordLengthError: 'የይለፍ ቃል ቢያንስ 8 ሆኖ ፊደል (a-z)፣ ቁጥር (0-9) እና ልዩ ምልክት (@, #, $, ወዘተ) ማካተት አለበት።',
    passwordRequirements: 'የይለፍ ቃል መስፈርቶች፦',
    reqMin8: 'ቢያንስ 8 ፊደላት/ቁምፊዎች',
    reqLetter: 'ፊደል ያካተተ (a-z, A-Z)',
    reqNumber: 'ቁጥር ያካተተ (0-9)',
    reqSymbol: 'ልዩ ምልክት ያካተተ (!@#$%^&*)',
    invalidResetLink: 'ይህ የይለፍ ቃል መቀየሪያ ሊንክ ትክክል አይደለም ወይም ጊዜው አልፏል።',
    resetLinkSentSuccess: 'የይለፍ ቃል መቀየሪያ ሊንክ ወደ ኢሜይልዎ ተልኳል፤ እባክዎ ኢሜይልዎን (Inbox ወይም Spam ፎልደር) ከፍተው ሊንኩን በመጫን የይለፍ ቃልዎን ይቀይሩ።'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('shered_res_lang') || 'am');

  const toggleLanguage = () => {
    const nextLang = lang === 'en' ? 'am' : 'en';
    setLang(nextLang);
    localStorage.setItem('shered_res_lang', nextLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

